/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package minesweeper.frames;

/**
 *
 * @author mattnorthgrave
 */
public class IntermediateBoard extends javax.swing.JFrame {

    /**
     * Creates new form IntermediateBoard
     */
    public IntermediateBoard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBox1 = new javax.swing.JCheckBox();
        jTextField2 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jA1Button = new javax.swing.JButton();
        jA2Button = new javax.swing.JButton();
        jA3Button = new javax.swing.JButton();
        jA4Button = new javax.swing.JButton();
        jA5Button = new javax.swing.JButton();
        jB1Button = new javax.swing.JButton();
        jB2Button = new javax.swing.JButton();
        jB3Button = new javax.swing.JButton();
        jB4Button = new javax.swing.JButton();
        jB5Button = new javax.swing.JButton();
        jC1Button = new javax.swing.JButton();
        jC2Button = new javax.swing.JButton();
        jC3Button = new javax.swing.JButton();
        jC4Button = new javax.swing.JButton();
        jC5Button = new javax.swing.JButton();
        jD1Button = new javax.swing.JButton();
        jD2Button = new javax.swing.JButton();
        jD3Button = new javax.swing.JButton();
        jD4Button = new javax.swing.JButton();
        jD5Button = new javax.swing.JButton();
        jE1Button = new javax.swing.JButton();
        jE2Button = new javax.swing.JButton();
        jE3Button = new javax.swing.JButton();
        jE4Button = new javax.swing.JButton();
        jE5Button = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();

        jCheckBox1.setText("jCheckBox1");

        jTextField2.setBackground(new java.awt.Color(0, 0, 153));
        jTextField2.setFont(new java.awt.Font("Menlo", 0, 24)); // NOI18N
        jTextField2.setText("jTextField2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(68, 205, 182));

        jA1Button.setFont(new java.awt.Font("Menlo", 0, 24)); // NOI18N
        jA1Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jA1ButtonActionPerformed(evt);
            }
        });

        jA2Button.setFont(new java.awt.Font("Menlo", 0, 24)); // NOI18N
        jA2Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jA2ButtonActionPerformed(evt);
            }
        });

        jA3Button.setFont(new java.awt.Font("Menlo", 0, 24)); // NOI18N
        jA3Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jA3ButtonActionPerformed(evt);
            }
        });

        jA4Button.setFont(new java.awt.Font("Menlo", 0, 24)); // NOI18N
        jA4Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jA4ButtonActionPerformed(evt);
            }
        });

        jA5Button.setFont(new java.awt.Font("Menlo", 0, 24)); // NOI18N
        jA5Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jA5ButtonActionPerformed(evt);
            }
        });

        jB1Button.setFont(new java.awt.Font("Menlo", 0, 24)); // NOI18N
        jB1Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB1ButtonActionPerformed(evt);
            }
        });

        jB2Button.setFont(new java.awt.Font("Menlo", 0, 24)); // NOI18N
        jB2Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB2ButtonActionPerformed(evt);
            }
        });

        jB3Button.setFont(new java.awt.Font("Menlo", 0, 24)); // NOI18N
        jB3Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB3ButtonActionPerformed(evt);
            }
        });

        jB4Button.setFont(new java.awt.Font("Menlo", 0, 24)); // NOI18N
        jB4Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB4ButtonActionPerformed(evt);
            }
        });

        jB5Button.setFont(new java.awt.Font("Menlo", 0, 24)); // NOI18N
        jB5Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB5ButtonActionPerformed(evt);
            }
        });

        jC1Button.setFont(new java.awt.Font("Menlo", 0, 24)); // NOI18N
        jC1Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jC1ButtonActionPerformed(evt);
            }
        });

        jC2Button.setFont(new java.awt.Font("Menlo", 0, 24)); // NOI18N
        jC2Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jC2ButtonActionPerformed(evt);
            }
        });

        jC3Button.setFont(new java.awt.Font("Menlo", 0, 24)); // NOI18N
        jC3Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jC3ButtonActionPerformed(evt);
            }
        });

        jC4Button.setFont(new java.awt.Font("Menlo", 0, 24)); // NOI18N
        jC4Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jC4ButtonActionPerformed(evt);
            }
        });

        jC5Button.setFont(new java.awt.Font("Menlo", 0, 24)); // NOI18N
        jC5Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jC5ButtonActionPerformed(evt);
            }
        });

        jD1Button.setFont(new java.awt.Font("Menlo", 0, 24)); // NOI18N
        jD1Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jD1ButtonActionPerformed(evt);
            }
        });

        jD2Button.setFont(new java.awt.Font("Menlo", 0, 24)); // NOI18N
        jD2Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jD2ButtonActionPerformed(evt);
            }
        });

        jD3Button.setFont(new java.awt.Font("Menlo", 0, 24)); // NOI18N
        jD3Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jD3ButtonActionPerformed(evt);
            }
        });

        jD4Button.setFont(new java.awt.Font("Menlo", 0, 24)); // NOI18N
        jD4Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jD4ButtonActionPerformed(evt);
            }
        });

        jD5Button.setFont(new java.awt.Font("Menlo", 0, 24)); // NOI18N
        jD5Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jD5ButtonActionPerformed(evt);
            }
        });

        jE1Button.setFont(new java.awt.Font("Menlo", 0, 24)); // NOI18N
        jE1Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jE1ButtonActionPerformed(evt);
            }
        });

        jE2Button.setFont(new java.awt.Font("Menlo", 0, 24)); // NOI18N
        jE2Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jE2ButtonActionPerformed(evt);
            }
        });

        jE3Button.setFont(new java.awt.Font("Menlo", 0, 24)); // NOI18N
        jE3Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jE3ButtonActionPerformed(evt);
            }
        });

        jE4Button.setFont(new java.awt.Font("Menlo", 0, 24)); // NOI18N
        jE4Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jE4ButtonActionPerformed(evt);
            }
        });

        jE5Button.setFont(new java.awt.Font("Menlo", 0, 24)); // NOI18N
        jE5Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jE5ButtonActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(0, 0, 153));

        jTextField1.setBackground(new java.awt.Color(0, 0, 153));
        jTextField1.setFont(new java.awt.Font("Menlo", 1, 36)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(255, 255, 255));
        jTextField1.setText("Intermediate");
        jTextField1.setBorder(null);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(166, 166, 166)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(135, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jD1Button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jC1Button, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jD2Button, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jD3Button, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jD4Button, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jD5Button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jB2Button, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jB3Button, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jB4Button, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jA1Button, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jA2Button, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jA3Button, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jA4Button, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jA5Button, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jB5Button, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jB1Button, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jE1Button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jE2Button, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jE3Button, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jE4Button, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jE5Button, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(jC2Button, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jC3Button, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jC4Button, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jC5Button, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(45, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jA5Button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jA4Button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jA1Button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jA3Button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jA2Button, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jB1Button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jB2Button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jB3Button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jB4Button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jB5Button, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jC1Button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jC2Button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jC3Button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jC4Button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jC5Button, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jD1Button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jD2Button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jD3Button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jD5Button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jD4Button, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jE1Button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jE2Button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jE3Button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jE4Button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jE5Button, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jA1ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jA1ButtonActionPerformed
        jA1Button.setText("1");        // TODO add your handling code here:
    }//GEN-LAST:event_jA1ButtonActionPerformed

    private void jA2ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jA2ButtonActionPerformed
        jA2Button.setText("1");        // TODO add your handling code here:
    }//GEN-LAST:event_jA2ButtonActionPerformed

    private void jA3ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jA3ButtonActionPerformed
        jA3Button.setText("2");        // TODO add your handling code here:
    }//GEN-LAST:event_jA3ButtonActionPerformed

    private void jA4ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jA4ButtonActionPerformed
        jA4Button.setText("1");        // TODO add your handling code here:
    }//GEN-LAST:event_jA4ButtonActionPerformed

    private void jA5ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jA5ButtonActionPerformed
        jA5Button.setText("1");        // TODO add your handling code here:
    }//GEN-LAST:event_jA5ButtonActionPerformed

    private void jB1ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB1ButtonActionPerformed
        jB1Button.setText("1");        // TODO add your handling code here:
    }//GEN-LAST:event_jB1ButtonActionPerformed

    private void jB2ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB2ButtonActionPerformed
        jB2Button.setText("*");
        this.dispose();
        GameOver over = new GameOver();
        over.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jB2ButtonActionPerformed

    private void jB3ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB3ButtonActionPerformed
        jB3Button.setText("2");        // TODO add your handling code here:
    }//GEN-LAST:event_jB3ButtonActionPerformed

    private void jB4ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB4ButtonActionPerformed
        jB4Button.setText("*");
        this.dispose();
        GameOver over = new GameOver();
        over.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jB4ButtonActionPerformed

    private void jB5ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB5ButtonActionPerformed
        jB5Button.setText("1");        // TODO add your handling code here:
    }//GEN-LAST:event_jB5ButtonActionPerformed

    private void jC1ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jC1ButtonActionPerformed
        jC1Button.setText("2");        // TODO add your handling code here:
    }//GEN-LAST:event_jC1ButtonActionPerformed

    private void jC2ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jC2ButtonActionPerformed
        jC2Button.setText("2");        // TODO add your handling code here:
    }//GEN-LAST:event_jC2ButtonActionPerformed

    private void jC3ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jC3ButtonActionPerformed
        jC3Button.setText("2");        // TODO add your handling code here:
    }//GEN-LAST:event_jC3ButtonActionPerformed

    private void jC4ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jC4ButtonActionPerformed
        jC4Button.setText("2");
    }//GEN-LAST:event_jC4ButtonActionPerformed

    private void jC5ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jC5ButtonActionPerformed
        jC5Button.setText("2");        // TODO add your handling code here:
    }//GEN-LAST:event_jC5ButtonActionPerformed

    private void jD1ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jD1ButtonActionPerformed
        jD1Button.setText("1");        // TODO add your handling code here:
    }//GEN-LAST:event_jD1ButtonActionPerformed

    private void jD2ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jD2ButtonActionPerformed
        jD2Button.setText("*");
        this.dispose();
        GameOver over = new GameOver();
        over.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jD2ButtonActionPerformed

    private void jD3ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jD3ButtonActionPerformed
        jD3Button.setText("2");        // TODO add your handling code here:
    }//GEN-LAST:event_jD3ButtonActionPerformed

    private void jD4ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jD4ButtonActionPerformed
        jD4Button.setText("*");
        this.dispose();
        GameOver over = new GameOver();
        over.setVisible(true);
// TODO add your handling code here:
    }//GEN-LAST:event_jD4ButtonActionPerformed

    private void jD5ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jD5ButtonActionPerformed
        jD5Button.setText("1");        // TODO add your handling code here:
    }//GEN-LAST:event_jD5ButtonActionPerformed

    private void jE1ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jE1ButtonActionPerformed
        jE1Button.setText("1");        // TODO add your handling code here:
    }//GEN-LAST:event_jE1ButtonActionPerformed

    private void jE2ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jE2ButtonActionPerformed
        jE2Button.setText("1");        // TODO add your handling code here:
    }//GEN-LAST:event_jE2ButtonActionPerformed

    private void jE3ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jE3ButtonActionPerformed
        jE3Button.setText("2");        // TODO add your handling code here:
    }//GEN-LAST:event_jE3ButtonActionPerformed

    private void jE4ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jE4ButtonActionPerformed
        jE4Button.setText("1");        // TODO add your handling code here:
    }//GEN-LAST:event_jE4ButtonActionPerformed

    private void jE5ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jE5ButtonActionPerformed
        jE5Button.setText("1");        // TODO add your handling code here:
    }//GEN-LAST:event_jE5ButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IntermediateBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IntermediateBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IntermediateBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IntermediateBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IntermediateBoard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jA1Button;
    private javax.swing.JButton jA2Button;
    private javax.swing.JButton jA3Button;
    private javax.swing.JButton jA4Button;
    private javax.swing.JButton jA5Button;
    private javax.swing.JButton jB1Button;
    private javax.swing.JButton jB2Button;
    private javax.swing.JButton jB3Button;
    private javax.swing.JButton jB4Button;
    private javax.swing.JButton jB5Button;
    private javax.swing.JButton jC1Button;
    private javax.swing.JButton jC2Button;
    private javax.swing.JButton jC3Button;
    private javax.swing.JButton jC4Button;
    private javax.swing.JButton jC5Button;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JButton jD1Button;
    private javax.swing.JButton jD2Button;
    private javax.swing.JButton jD3Button;
    private javax.swing.JButton jD4Button;
    private javax.swing.JButton jD5Button;
    private javax.swing.JButton jE1Button;
    private javax.swing.JButton jE2Button;
    private javax.swing.JButton jE3Button;
    private javax.swing.JButton jE4Button;
    private javax.swing.JButton jE5Button;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
